import type { Snapshot, ProductData } from '../types';
import { processRawData, processMfiData, calculateStats, MfiData } from './dataProcessor';

// August 2026 Raw Snapshot Data (Current)
const rawSnapshotAugust = [
    {
        'sku': 'ANC-HEADPHONE-PRO',
        'asin': 'B09X1A2B3C',
        'product-name': 'Active Noise Cancelling Wireless Over-Ear Headphones Pro',
        'condition': 'New',
        'available': '18',
        'units-shipped-t30': '320',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '18',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'USB-C-HUB-7IN1',
        'asin': 'B08Y2C3D4E',
        'product-name': 'Aluminum 7-in-1 USB-C Hub Adapter with 4K HDMI & 100W PD',
        'condition': 'New',
        'available': '145',
        'units-shipped-t30': '180',
        'pending-removal-quantity': '2',
        'inv-age-0-to-90-days': '130',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'ERGONOMIC-MOUSE-WL',
        'asin': 'B07Z3D4E5F',
        'product-name': 'Ergonomic Vertical Wireless Mouse with Silent Click',
        'condition': 'New',
        'available': '85',
        'units-shipped-t30': '95',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '70',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'WIRELESS-PAD-15W',
        'asin': 'B07W4E5F6G',
        'product-name': 'Ultra-Slim 15W Fast Qi Wireless Charging Pad',
        'condition': 'New',
        'available': '210',
        'units-shipped-t30': '12',
        'pending-removal-quantity': '45',
        'inv-age-0-to-90-days': '10',
        'inv-age-91-to-180-days': '40',
        'inv-age-181-to-270-days': '80',
        'inv-age-271-to-365-days': '50',
        'inv-age-365-plus-days': '30',
        'recommended-action': 'Recommended Removal',
        'category': 'Electronics',
    },
    {
        'sku': 'MECH-KEYBOARD-RGB',
        'asin': 'B09V5F6G7H',
        'product-name': 'Tenkeyless Mechanical Gaming Keyboard RGB Hot-Swappable',
        'condition': 'New',
        'available': '62',
        'units-shipped-t30': '110',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '62',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'BT-SPEAKER-MINI',
        'asin': 'B08U6G7H8J',
        'product-name': 'Pocket Waterproof Bluetooth 5.3 Speaker with Enhanced Bass',
        'condition': 'New',
        'available': '120',
        'units-shipped-t30': '0',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '20',
        'inv-age-91-to-180-days': '60',
        'inv-age-181-to-270-days': '40',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'FRENCH-PRESS-34OZ',
        'asin': 'B08T7H8J9K',
        'product-name': 'Double Wall Insulated Stainless Steel French Press 34oz',
        'condition': 'New',
        'available': '92',
        'units-shipped-t30': '210',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '92',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'SILICONE-UTENSIL-12P',
        'asin': 'B09S8J9K0L',
        'product-name': 'Non-Stick Heat Resistant Silicone Cooking Utensils 12-Piece Set',
        'condition': 'New',
        'available': '160',
        'units-shipped-t30': '140',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '120',
        'inv-age-91-to-180-days': '40',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'POUR-OVER-CERAMIC',
        'asin': 'B07R9K0L1M',
        'product-name': 'Ceramic Pour Over Coffee Dripper Single Cup Brewer',
        'condition': 'New',
        'available': '74',
        'units-shipped-t30': '65',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '50',
        'inv-age-91-to-180-days': '24',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'VACUUM-TUMBLER-32OZ',
        'asin': 'B09Q0L1M2N',
        'product-name': 'Insulated Stainless Steel Travel Tumbler with Straw Lid 32oz',
        'condition': 'New',
        'available': '24',
        'units-shipped-t30': '240',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '24',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'MILK-FROTHER-HAND',
        'asin': 'B08P1M2N3P',
        'product-name': 'Electric Handheld Milk Frother Foam Maker for Coffee',
        'condition': 'New',
        'available': '180',
        'units-shipped-t30': '175',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '150',
        'inv-age-91-to-180-days': '30',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'CAST-IRON-SKILLET-10',
        'asin': 'B07N2N3P4Q',
        'product-name': 'Pre-Seasoned Cast Iron Skillet Pan 10.25-Inch with Silicone Handle',
        'condition': 'New',
        'available': '95',
        'units-shipped-t30': '18',
        'pending-removal-quantity': '10',
        'inv-age-0-to-90-days': '0',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '45',
        'inv-age-271-to-365-days': '35',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'Recommended Removal',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'DESK-CONVERTER-36',
        'asin': 'B08M3P4Q5R',
        'product-name': 'Height Adjustable Standing Desk Converter 36-Inch Dual Tier',
        'condition': 'New',
        'available': '38',
        'units-shipped-t30': '42',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '18',
        'inv-age-91-to-180-days': '20',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Office Products',
    },
    {
        'sku': 'GEL-WRIST-REST-PAD',
        'asin': 'B07L4Q5R6S',
        'product-name': 'Ergonomic Memory Foam Mouse Pad with Gel Wrist Rest Support',
        'condition': 'New',
        'available': '115',
        'units-shipped-t30': '135',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '100',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Office Products',
    },
    {
        'sku': 'MESH-DESK-ORGANIZER',
        'asin': 'B06K5R6S7T',
        'product-name': 'All-in-One 5-Tier Mesh Metal Desk Organizer with Drawer',
        'condition': 'New',
        'available': '165',
        'units-shipped-t30': '8',
        'pending-removal-quantity': '65',
        'inv-age-0-to-90-days': '0',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '30',
        'inv-age-271-to-365-days': '40',
        'inv-age-365-plus-days': '80',
        'recommended-action': 'Recommended Removal',
        'category': 'Office Products',
    },
    {
        'sku': 'BLUE-LIGHT-GLASSES-2PK',
        'asin': 'B09J6S7T8U',
        'product-name': 'Blue Light Blocking Computer Reading Glasses 2-Pack Unisex',
        'condition': 'New',
        'available': '140',
        'units-shipped-t30': '190',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '125',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Office Products',
    },
    {
        'sku': 'RESISTANCE-BANDS-SET',
        'asin': 'B08H7T8U9V',
        'product-name': 'Heavy Duty Exercise Loop Resistance Workout Bands 5-Pack',
        'condition': 'New',
        'available': '45',
        'units-shipped-t30': '235',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '45',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Sports & Outdoors',
    },
    {
        'sku': 'FOAM-ROLLER-DEEP-36',
        'asin': 'B07G8U9V0W',
        'product-name': 'High Density Deep Tissue Muscle Foam Roller 36-Inch',
        'condition': 'New',
        'available': '110',
        'units-shipped-t30': '14',
        'pending-removal-quantity': '50',
        'inv-age-0-to-90-days': '0',
        'inv-age-91-to-180-days': '20',
        'inv-age-181-to-270-days': '40',
        'inv-age-271-to-365-days': '30',
        'inv-age-365-plus-days': '20',
        'recommended-action': 'Recommended Removal',
        'category': 'Sports & Outdoors',
    },
    {
        'sku': 'MICROFIBER-TOWEL-XL',
        'asin': 'B09F9V0W1X',
        'product-name': 'Fast Drying Microfiber Travel & Beach Towel with Carry Bag XL',
        'condition': 'New',
        'available': '88',
        'units-shipped-t30': '98',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '75',
        'inv-age-91-to-180-days': '13',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Sports & Outdoors',
    },
    {
        'sku': 'SHIATSU-NECK-MASSAGER',
        'asin': 'B08D0W1X2Y',
        'product-name': 'Heated 3D Deep Kneading Shiatsu Neck and Shoulder Massager',
        'condition': 'New',
        'available': '32',
        'units-shipped-t30': '160',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '32',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Health & Personal Care',
    },
    {
        'sku': 'SONIC-TOOTHBRUSH-UV',
        'asin': 'B09C1X2Y3Z',
        'product-name': 'Rechargeable Sonic Electric Toothbrush with UV Sanitizing Case',
        'condition': 'New',
        'available': '125',
        'units-shipped-t30': '115',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '95',
        'inv-age-91-to-180-days': '30',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Health & Personal Care',
    },
    {
        'sku': 'MASSAGE-GUN-PERCUSSION',
        'asin': 'B07B2Y3Z4A',
        'product-name': 'Cordless Deep Tissue Percussion Massage Gun 6 Heads',
        'condition': 'New',
        'available': '85',
        'units-shipped-t30': '15',
        'pending-removal-quantity': '25',
        'inv-age-0-to-90-days': '0',
        'inv-age-91-to-180-days': '10',
        'inv-age-181-to-270-days': '20',
        'inv-age-271-to-365-days': '25',
        'inv-age-365-plus-days': '30',
        'recommended-action': 'Recommended Removal',
        'category': 'Health & Personal Care',
    },
];

// Raw MFI Logistics Data for August 2026
const rawMfiAugust = [
    {
        'sku': 'ANC-HEADPHONE-PRO',
        'afn-inbound-working-quantity': '50',
        'afn-inbound-shipped-quantity': '200',
        'afn-inbound-receiving-quantity': '0',
        'afn-reserved-quantity': '6',
        'mfn-fulfillable-quantity': '0',
    },
    {
        'sku': 'USB-C-HUB-7IN1',
        'afn-inbound-working-quantity': '0',
        'afn-inbound-shipped-quantity': '100',
        'afn-inbound-receiving-quantity': '0',
        'afn-reserved-quantity': '8',
        'mfn-fulfillable-quantity': '0',
    },
    {
        'sku': 'VACUUM-TUMBLER-32OZ',
        'afn-inbound-working-quantity': '150',
        'afn-inbound-shipped-quantity': '0',
        'afn-inbound-receiving-quantity': '0',
        'afn-reserved-quantity': '4',
        'mfn-fulfillable-quantity': '0',
    },
    {
        'sku': 'RESISTANCE-BANDS-SET',
        'afn-inbound-working-quantity': '0',
        'afn-inbound-shipped-quantity': '300',
        'afn-inbound-receiving-quantity': '50',
        'afn-reserved-quantity': '12',
        'mfn-fulfillable-quantity': '0',
    },
    {
        'sku': 'SHIATSU-NECK-MASSAGER',
        'afn-inbound-working-quantity': '0',
        'afn-inbound-shipped-quantity': '120',
        'afn-inbound-receiving-quantity': '0',
        'afn-reserved-quantity': '5',
        'mfn-fulfillable-quantity': '0',
    },
    {
        'sku': 'FRENCH-PRESS-34OZ',
        'afn-inbound-working-quantity': '0',
        'afn-inbound-shipped-quantity': '150',
        'afn-inbound-receiving-quantity': '0',
        'afn-reserved-quantity': '7',
        'mfn-fulfillable-quantity': '0',
    },
    {
        'sku': 'MESH-DESK-ORGANIZER',
        'afn-inbound-working-quantity': '0',
        'afn-inbound-shipped-quantity': '0',
        'afn-inbound-receiving-quantity': '0',
        'afn-reserved-quantity': '2',
        'mfn-fulfillable-quantity': '0',
    },
];

// July 2026 Raw Snapshot Data (Historical Comparison Snapshot)
const rawSnapshotJuly = [
    {
        'sku': 'ANC-HEADPHONE-PRO',
        'asin': 'B09X1A2B3C',
        'product-name': 'Active Noise Cancelling Wireless Over-Ear Headphones Pro',
        'condition': 'New',
        'available': '120',
        'units-shipped-t30': '250',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '120',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'USB-C-HUB-7IN1',
        'asin': 'B08Y2C3D4E',
        'product-name': 'Aluminum 7-in-1 USB-C Hub Adapter with 4K HDMI & 100W PD',
        'condition': 'New',
        'available': '190',
        'units-shipped-t30': '165',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '180',
        'inv-age-91-to-180-days': '10',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'ERGONOMIC-MOUSE-WL',
        'asin': 'B07Z3D4E5F',
        'product-name': 'Ergonomic Vertical Wireless Mouse with Silent Click',
        'condition': 'New',
        'available': '98',
        'units-shipped-t30': '90',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '85',
        'inv-age-91-to-180-days': '13',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'WIRELESS-PAD-15W',
        'asin': 'B07W4E5F6G',
        'product-name': 'Ultra-Slim 15W Fast Qi Wireless Charging Pad',
        'condition': 'New',
        'available': '225',
        'units-shipped-t30': '28',
        'pending-removal-quantity': '20',
        'inv-age-0-to-90-days': '20',
        'inv-age-91-to-180-days': '60',
        'inv-age-181-to-270-days': '95',
        'inv-age-271-to-365-days': '50',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'Recommended Removal',
        'category': 'Electronics',
    },
    {
        'sku': 'MECH-KEYBOARD-RGB',
        'asin': 'B09V5F6G7H',
        'product-name': 'Tenkeyless Mechanical Gaming Keyboard RGB Hot-Swappable',
        'condition': 'New',
        'available': '85',
        'units-shipped-t30': '95',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '85',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'BT-SPEAKER-MINI',
        'asin': 'B08U6G7H8J',
        'product-name': 'Pocket Waterproof Bluetooth 5.3 Speaker with Enhanced Bass',
        'condition': 'New',
        'available': '120',
        'units-shipped-t30': '15',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '40',
        'inv-age-91-to-180-days': '80',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Electronics',
    },
    {
        'sku': 'FRENCH-PRESS-34OZ',
        'asin': 'B08T7H8J9K',
        'product-name': 'Double Wall Insulated Stainless Steel French Press 34oz',
        'condition': 'New',
        'available': '140',
        'units-shipped-t30': '145',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '140',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'SILICONE-UTENSIL-12P',
        'asin': 'B09S8J9K0L',
        'product-name': 'Non-Stick Heat Resistant Silicone Cooking Utensils 12-Piece Set',
        'condition': 'New',
        'available': '175',
        'units-shipped-t30': '130',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '145',
        'inv-age-91-to-180-days': '30',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'POUR-OVER-CERAMIC',
        'asin': 'B07R9K0L1M',
        'product-name': 'Ceramic Pour Over Coffee Dripper Single Cup Brewer',
        'condition': 'New',
        'available': '88',
        'units-shipped-t30': '60',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '70',
        'inv-age-91-to-180-days': '18',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'VACUUM-TUMBLER-32OZ',
        'asin': 'B09Q0L1M2N',
        'product-name': 'Insulated Stainless Steel Travel Tumbler with Straw Lid 32oz',
        'condition': 'New',
        'available': '130',
        'units-shipped-t30': '210',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '130',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'MILK-FROTHER-HAND',
        'asin': 'B08P1M2N3P',
        'product-name': 'Electric Handheld Milk Frother Foam Maker for Coffee',
        'condition': 'New',
        'available': '210',
        'units-shipped-t30': '160',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '190',
        'inv-age-91-to-180-days': '20',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'CAST-IRON-SKILLET-10',
        'asin': 'B07N2N3P4Q',
        'product-name': 'Pre-Seasoned Cast Iron Skillet Pan 10.25-Inch with Silicone Handle',
        'condition': 'New',
        'available': '108',
        'units-shipped-t30': '24',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '10',
        'inv-age-91-to-180-days': '30',
        'inv-age-181-to-270-days': '68',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'Recommended Removal',
        'category': 'Home & Kitchen',
    },
    {
        'sku': 'DESK-CONVERTER-36',
        'asin': 'B08M3P4Q5R',
        'product-name': 'Height Adjustable Standing Desk Converter 36-Inch Dual Tier',
        'condition': 'New',
        'available': '45',
        'units-shipped-t30': '38',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '25',
        'inv-age-91-to-180-days': '20',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Office Products',
    },
    {
        'sku': 'GEL-WRIST-REST-PAD',
        'asin': 'B07L4Q5R6S',
        'product-name': 'Ergonomic Memory Foam Mouse Pad with Gel Wrist Rest Support',
        'condition': 'New',
        'available': '130',
        'units-shipped-t30': '125',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '115',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Office Products',
    },
    {
        'sku': 'MESH-DESK-ORGANIZER',
        'asin': 'B06K5R6S7T',
        'product-name': 'All-in-One 5-Tier Mesh Metal Desk Organizer with Drawer',
        'condition': 'New',
        'available': '180',
        'units-shipped-t30': '16',
        'pending-removal-quantity': '20',
        'inv-age-0-to-90-days': '0',
        'inv-age-91-to-180-days': '25',
        'inv-age-181-to-270-days': '45',
        'inv-age-271-to-365-days': '50',
        'inv-age-365-plus-days': '60',
        'recommended-action': 'Recommended Removal',
        'category': 'Office Products',
    },
    {
        'sku': 'BLUE-LIGHT-GLASSES-2PK',
        'asin': 'B09J6S7T8U',
        'product-name': 'Blue Light Blocking Computer Reading Glasses 2-Pack Unisex',
        'condition': 'New',
        'available': '160',
        'units-shipped-t30': '170',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '145',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Office Products',
    },
    {
        'sku': 'RESISTANCE-BANDS-SET',
        'asin': 'B08H7T8U9V',
        'product-name': 'Heavy Duty Exercise Loop Resistance Workout Bands 5-Pack',
        'condition': 'New',
        'available': '140',
        'units-shipped-t30': '210',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '140',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Sports & Outdoors',
    },
    {
        'sku': 'FOAM-ROLLER-DEEP-36',
        'asin': 'B07G8U9V0W',
        'product-name': 'High Density Deep Tissue Muscle Foam Roller 36-Inch',
        'condition': 'New',
        'available': '125',
        'units-shipped-t30': '32',
        'pending-removal-quantity': '20',
        'inv-age-0-to-90-days': '10',
        'inv-age-91-to-180-days': '35',
        'inv-age-181-to-270-days': '45',
        'inv-age-271-to-365-days': '35',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'Recommended Removal',
        'category': 'Sports & Outdoors',
    },
    {
        'sku': 'MICROFIBER-TOWEL-XL',
        'asin': 'B09F9V0W1X',
        'product-name': 'Fast Drying Microfiber Travel & Beach Towel with Carry Bag XL',
        'condition': 'New',
        'available': '95',
        'units-shipped-t30': '90',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '85',
        'inv-age-91-to-180-days': '10',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Sports & Outdoors',
    },
    {
        'sku': 'SHIATSU-NECK-MASSAGER',
        'asin': 'B08D0W1X2Y',
        'product-name': 'Heated 3D Deep Kneading Shiatsu Neck and Shoulder Massager',
        'condition': 'New',
        'available': '85',
        'units-shipped-t30': '145',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '85',
        'inv-age-91-to-180-days': '0',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Health & Personal Care',
    },
    {
        'sku': 'SONIC-TOOTHBRUSH-UV',
        'asin': 'B09C1X2Y3Z',
        'product-name': 'Rechargeable Sonic Electric Toothbrush with UV Sanitizing Case',
        'condition': 'New',
        'available': '140',
        'units-shipped-t30': '105',
        'pending-removal-quantity': '0',
        'inv-age-0-to-90-days': '115',
        'inv-age-91-to-180-days': '25',
        'inv-age-181-to-270-days': '0',
        'inv-age-271-to-365-days': '0',
        'inv-age-365-plus-days': '0',
        'recommended-action': 'No Action',
        'category': 'Health & Personal Care',
    },
    {
        'sku': 'MASSAGE-GUN-PERCUSSION',
        'asin': 'B07B2Y3Z4A',
        'product-name': 'Cordless Deep Tissue Percussion Massage Gun 6 Heads',
        'condition': 'New',
        'available': '95',
        'units-shipped-t30': '22',
        'pending-removal-quantity': '10',
        'inv-age-0-to-90-days': '5',
        'inv-age-91-to-180-days': '15',
        'inv-age-181-to-270-days': '25',
        'inv-age-271-to-365-days': '30',
        'inv-age-365-plus-days': '20',
        'recommended-action': 'Recommended Removal',
        'category': 'Health & Personal Care',
    },
];

export interface SampleDataPackage {
    snapshots: Record<string, Snapshot>;
    activeSnapshotKey: string;
    insights: string[];
}

export const getSampleSnapshots = (): SampleDataPackage => {
    const mfiMapAugust = processMfiData(rawMfiAugust);

    // Process August Snapshot (Current)
    const dataAugust = processRawData(rawSnapshotAugust, mfiMapAugust);
    const statsAugust = calculateStats(dataAugust);
    const snapshotAugust: Snapshot = {
        name: 'Demo FBA Snapshot - August 2026',
        data: dataAugust,
        stats: statsAugust,
        timestamp: '2026-08-15T10:00:00.000Z',
    };

    // Process July Snapshot (Historical Base)
    const dataJuly = processRawData(rawSnapshotJuly);
    const statsJuly = calculateStats(dataJuly);
    const snapshotJuly: Snapshot = {
        name: 'Demo FBA Snapshot - July 2026',
        data: dataJuly,
        stats: statsJuly,
        timestamp: '2026-07-15T10:00:00.000Z',
    };

    const snapshots: Record<string, Snapshot> = {
        'demo_fba_snapshot_2026_07': snapshotJuly,
        'demo_fba_snapshot_2026_08': snapshotAugust,
    };

    const insights = [
        "Stockout Imminent on Top Earner: SKU 'ANC-HEADPHONE-PRO' has only 18 units available with 320 sold in 30 days (< 2 days of cover). Expedite check-in of the 200 inbound units currently in transit.",
        "Long-Term Storage Fee Exposure: Over 130 units across 'MESH-DESK-ORGANIZER', 'WIRELESS-PAD-15W', and 'MASSAGE-GUN-PERCUSSION' exceed 365 days of age. Prioritize automated removal orders or create a 25% liquidation coupon.",
        "High Velocity Outperformer: 'FRENCH-PRESS-34OZ' demonstrated a +45% sales surge month-over-month with an 70% sell-through rate. Consider expanding color variants and increasing safety stock buffer.",
        "Stranded Inventory Identified: 'BT-SPEAKER-MINI' holds 120 units in FBA with zero sales in the last 30 days. Investigate whether the listing is suppressed or Buy Box is inactive.",
        "Logistics Balance: Total account sell-through stands at 56% with an average inventory age of 67 days, reflecting healthy core turnover across Home & Electronics lines."
    ];

    return {
        snapshots,
        activeSnapshotKey: 'demo_fba_snapshot_2026_08',
        insights,
    };
};
