import React from 'react';
import { useAppContext } from '../state/appContext';
import { RocketIcon, CompareIcon, ExportIcon, SearchIcon, LightbulbIcon, BarChartIcon, CogIcon, SparklesIcon, FlagIcon } from './Icons';

const HelpSection: React.FC<{ title: string; icon: React.ReactNode; children: React.ReactNode }> = ({ title, icon, children }) => (
    <div className="border-t border-gray-200 pt-4 mt-4 first:mt-0 first:border-t-0 first:pt-0">
        <h3 className="text-lg font-bold text-gray-800 flex items-center mb-2">
            <span className="text-[#9c4dff] mr-2">{icon}</span>
            {title}
        </h3>
        <div className="text-sm text-gray-600 space-y-2">
            {children}
        </div>
    </div>
);

const HelpModal: React.FC = () => {
    const { dispatch } = useAppContext();

    const handleClose = () => {
        // FIX: Corrected typo in dispatch action type.
        dispatch({ type: 'CLOSE_HELP_MODAL' });
    };

    return (
        <div 
            className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4 backdrop-blur-sm" 
            onClick={handleClose} 
            role="dialog" 
            aria-modal="true" 
            aria-labelledby="help-modal-title"
        >
            <div 
                className="bg-white rounded-xl shadow-2xl w-full max-w-2xl flex flex-col" 
                onClick={e => e.stopPropagation()}
                style={{ maxHeight: '90vh' }}
            >
                <div className="p-6 border-b border-gray-200 flex justify-between items-center flex-shrink-0">
                    <h2 id="help-modal-title" className="text-xl font-bold text-gray-800">WesBI User Guide</h2>
                    <button 
                        onClick={handleClose} 
                        className="text-gray-400 hover:text-gray-600 transition-colors"
                        aria-label="Close help modal"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                
                <div className="p-6 overflow-y-auto">
                    <HelpSection title="Getting Started" icon={<RocketIcon />}>
                        <p>Click the <strong>"Upload & Process"</strong> button to select one or more FBA Snapshot <code>.csv</code> files from your computer. WesBI will automatically process them, calculate key metrics, and generate AI-powered insights.</p>
                    </HelpSection>

                    <HelpSection title="The Dashboard" icon={<BarChartIcon className="w-5 h-5" />}>
                        <p>Your main dashboard provides an at-a-glance overview of your business health:</p>
                        <ul className="list-disc list-inside pl-4 space-y-1">
                            <li><strong>Stat Cards:</strong> Key performance indicators (KPIs) are displayed at the top. In comparison mode, these show changes over time.</li>
                            <li><strong>AI Insights:</strong> Actionable recommendations generated by Gemini to help you optimize your inventory.</li>
                            <li><strong>Charts:</strong> Visual breakdowns of inventory age, high-risk SKUs, and top-performing products.</li>
                        </ul>
                    </HelpSection>

                    <HelpSection title="Settings & Configuration" icon={<CogIcon className="w-5 h-5" />}>
                        <p>Customize your experience by clicking the <strong>cog icon</strong> in the header:</p>
                        <ul className="list-disc list-inside pl-4 space-y-1">
                            <li><strong>Gemini API Key:</strong> To unlock the "AI-Powered Insights" feature, you must provide your own Google Gemini API key. Your key is stored securely in your browser and is never sent to our servers.</li>
                            <li><strong>Enable AI Features:</strong> You can toggle the AI analysis on or off. If disabled, the app will function as a standard data analyzer without making any API calls.</li>
                        </ul>
                    </HelpSection>

                    <HelpSection title="AI Strategy Session" icon={<SparklesIcon className="w-5 h-5" />}>
                        <p>Go beyond insights and generate a complete operational playbook. This feature uses AI to build a step-by-step action plan based on your current data.</p>
                        <ul className="list-disc list-inside pl-4 space-y-1">
                            <li>Click the <strong>"AI Strategy Session"</strong> button.</li>
                            <li>Select a high-level business goal from the dropdown, such as "Liquidate High-Risk Inventory".</li>
                            <li>WesBI will analyze your snapshot and generate a detailed plan, including specific SKUs to focus on, to achieve your objective.</li>
                        </ul>
                    </HelpSection>

                     <HelpSection title="Mission Control" icon={<FlagIcon className="w-5 h-5" />}>
                        <p>Turn your AI-generated strategy into a trackable mission. After generating a plan in the AI Strategy Session, click <strong>"Start Mission"</strong>.</p>
                        <ul className="list-disc list-inside pl-4 space-y-1">
                            <li>A new <strong>Mission Control</strong> panel will appear on your dashboard.</li>
                            <li><strong>KPI Chart:</strong> This chart tracks the primary metric for your mission's goal. It automatically updates every time you upload a new snapshot, showing your progress over time.</li>
                            <li><strong>Action Plan:</strong> The AI's step-by-step plan becomes an interactive checklist. Mark tasks as complete as you execute them.</li>
                            <li>When finished, you can mark the mission as <strong>Complete</strong> or <strong>Abort</strong> it.</li>
                        </ul>
                    </HelpSection>

                    <HelpSection title="Filtering & Searching" icon={<SearchIcon />}>
                        <p>Use the controls to drill down into your data. You can search by SKU, ASIN, or name. The filter dropdowns allow you to narrow your view by inventory age, recommended actions, stock status, and more. Click a column header in the table to sort by that metric.</p>
                    </HelpSection>

                    <HelpSection title="Comparing Snapshots" icon={<CompareIcon />}>
                        <p>To track performance over time, upload two different snapshots. Click the <strong>"Compare..."</strong> button, select an older "Base" snapshot and a newer "Compare" snapshot. The dashboard will update to show the changes (deltas) in your KPIs and in the data table for each SKU.</p>
                    </HelpSection>
                    
                    <HelpSection title="Restock Forecasting" icon={<LightbulbIcon className="w-5 h-5" />}>
                        <p>WesBI calculates a suggested restock quantity for each item based on its 30-day sales velocity. You can fine-tune these recommendations by adjusting:</p>
                        <ul className="list-disc list-inside pl-4 space-y-1">
                            <li><strong>Supplier Lead Time:</strong> How many days it takes for new stock to arrive.</li>
                            <li><strong>Safety Stock:</strong> The number of days of inventory you want as a buffer.</li>
                            <li><strong>Demand Forecast %:</strong> A percentage to increase or decrease the sales velocity for your forecast (e.g., 10% for an expected increase in demand).</li>
                        </ul>
                    </HelpSection>

                    <HelpSection title="Exporting Data" icon={<ExportIcon />}>
                        <p>Click the <strong>"Export"</strong> button to download your current view as a CSV file. The export will respect all active filters and the current sorting order, making it perfect for custom reports.</p>
                    </HelpSection>
                </div>
            </div>
        </div>
    );
};

export default HelpModal;